apiVersion: v1
kind: Secret
metadata:
  name: grid-qa-llm-user-integration
  namespace: REPLACE_GRID_QA_NAMESPACE
type: Opaque
stringData:
  LLM_USER_OBSERVER_USER_HASH_SECRET: REPLACE_ME
  LLM_USER_CALLBACK_SECRET: REPLACE_ME
  LLM_USER_SUITE_EVENT_SECRET: REPLACE_ME
